package com.team4.backend.testdata;

import com.team4.backend.dto.InternshipManagerCreationDto;
import com.team4.backend.model.InternshipManager;

public abstract class InternshipManagerMockData {

    public static InternshipManager GetInternshipManager() {
        return InternshipManager.internshipManagerBuilder()
                .id("internship_manager_id")
                .email("intership.manager@email.com")
                .firstName("John")
                .lastName("Doe")
                .password("password")
                .registrationDate(null) // Autogenerated (creation time) when null
                .build();
    }

    public static InternshipManagerCreationDto GetInternshipManagerDto() {
        return InternshipManagerCreationDto.builder()
                .id("internship_manager_id")
                .email("intership.manager@email.com")
                .firstName("John")
                .lastName("Doe")
                .password("password")
                .registrationDate(null) // Autogenerated (creation time) when null
                .build();
    }

}
