security:
  password:
    encoder:
      secret : mysecret
      iteration : 33
      keyLength : 256

  jwt:
    secret : ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration : 28800


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      resolve-lazily: true
      enabled: true
      location: /tmp

server:
  error:
    include-message: always
