
security:
  password:
    encoder:
      secret : mysecret
      iteration : 33
      keyLength : 256

  jwt:
    secret : ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration : 28800

server:
  error:
    include-message: always

spring:
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
      resolve-lazily: true
      enabled: true
      location: /tmp
