security:
  password:
    encoder:
      secret : mysecret
      iteration : 33
      keyLength : 256

  jwt:
    secret : ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration : 2880

